### ISSUE TITLE
Alternative ember template tags

### ISSUE THREAD

**Issue by scardine** [noirbizarre/django-ember#3]
The `handlebars` template tag behaves much like `verbatim`.

What do you think about the syntax proposed by https://github.com/scardine/django-ember-tag ?

I find it easier to use. Would you accept a pull request to merge it?

**Comment by noirbizarre** [comment]
Yes I will accept it as long as the original syntax is preserved and if you add some tests to the original library.
From what I see, both templates tags can coexists because they do not share the same name.

I'm waiting your pull request.
